### ISSUE TITLE
Add support for multiple files

### ISSUE THREAD

**Issue by teodoro-cangrejo** [Jack89ita/vscode-copy-filename#10]
In other editor (Jetbrains webstorm) i could select many files and copi them, then when pasted in text, the names are pasted each in a new line. This allowed me to add many files to a paths definition file. I would love to be able to work this way again in VSC.

**Comment by Jack89ita** [comment]
Hi @teodoro-cangrejo!
Thanks for the feedback and for helping me to improve the plugin with nice suggestion.
With the latest version (2.3.0) the support for copy multiple filenames has been added.
Feel free to reopen this issue if something goes wrong.

**Comment by teodoroSandoval** [comment]
really cool to have this, thanks for this feature and for your work on maintaining this.
