### ISSUE TITLE
Unwanted line break

### ISSUE THREAD

**Issue by simon-olsen** [Jack89ita/vscode-copy-filename#11]
Every time I paste the name of a file, it's adding an unwanted line break after. Regardless of whether I paste the file name into VS Code or into another program.

Also regardless of file extension.

This is only started happening recently. Was working perfectly before.

**Comment by Jack89ita** [comment]
Hi @simon-olsen, thank you for the feedback.
I have fixed this bug in the new version of the plugin.
Feel free to reopen the issue if you still have trouble.
Thank you!

**Comment by simon-olsen** [comment]
Just tested it out and there's no line-break anymore. Thanks very much for a speedy response and fix.
