### ISSUE TITLE
adding option for keeping filename extention

### ISSUE THREAD

**Issue by sagivd** [Jack89ita/vscode-copy-filename#12]
Hi,

first of all - thanks for publishing this extension! 👍 
Coming from slickedit, I was missing this feature..

I was wondering if you could add an option to the extension where "copy file name" would keep the file extention (as i usually use it that way).

thanks!

**Comment by Jack89ita** [comment]
Hi @sagivd,
this plugin should already copy the file extension. 
If you expect some kind of proble just reopen the this issue.
Thanks!

**Comment by sagivd** [comment]
Hi @Jack89ita 

this actually doesnt work in macos.
only the body of the filename is copied.


PS
I could not find how to reopen the issue here :)

**Comment by Jack89ita** [comment]
Hello @sagivd ,
i have just tried in vscode with a macos and it works as expected. Have you got some errors in the console panel of vscode? Can you tell me the vscode version and the pc model and OS?
Since i can't reproduce the issue in my machine it's difficult to fix.
Thanks!

**Comment by sagivd** [comment]
thats understandable..

i dont see any logs in the output/terminal/problems tabs.


vscode data:

Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z (1 wk ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0



macos version 10.15.5 

HW model:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1

**Comment by Jack89ita** [comment]
I have installed a virtual machine on my pc and it seems ok: it correctly get the extension while copying the name.
I've also updated some dependencies.
Try to see if it works with the new version.
Thanks!

**Comment by sagivd** [comment]
Thanks, it works now :)
