### ISSUE TITLE
Does not work like expected when in an image file

### ISSUE THREAD

**Issue by jenstornell** [Jack89ita/vscode-copy-filename#2]
1. In VSCode, click on an image to preview it.
1. When in the image preview click "Copy name to clipboard" on the image filename.
1. Go to a file where you want your filename to be pasted.
1. Try to paste it.

The filename is NOT in the clipboard. Instead it will paste the old clipboard data.

It however does work when has the code or text file open instead and not an image.

**Comment by SimonIMG** [comment]
Confirming that I'm having this same issue. If image is being previewed, the filename doesn't copy. It does when I have a code file displayed in the VS Code viewer.

**Comment by Jack89ita** [comment]
Hello guys!
Thanks for the feedback and sorry for taking so long to solve this.
Try to update and if you still have the problem open a new issue.

**Comment by SimonIMG** [comment]
Nice work! Confirming that I have v2.0.0 installed and I can copy a filename while the image is being previewed in VS Code.

- Tested with PNG, JPG and SVG (SVG being previewed or when the code is displayed).
- Also tested copying from on VS Code project window into another.
- Also tested when copying into a completely different application or browser.
