### ISSUE TITLE
Broken!  😢-I really like this extension😢

### ISSUE THREAD

**Issue by kaanuki** [Jack89ita/vscode-copy-filename#5]
This app is still broken in Windows 10, VS Code v1.33.1

**Comment by kaanuki** [comment]
Nevermind.  I have installed the 'Copy File name' extension by Viktor Nemes. The new version has added the ability to copy by Right-clicking.

**Comment by Jack89ita** [comment]
Hi @kaanuki, thank you for the feedback, can you give me some more information about your issue?
I've just updated the plugin, can you try it and see if it works?
Thank you!
